
### site meta

title: BBX TBZ ğŸ¤ğŸ¥ğŸµ
description: various beats & breaks, transcribed as tablature for beatboxing
author: eliran malka


### host settings

# omitting http:// at the start forces HTTPS
domain: eliranmal.github.io
url: https://eliranmal.github.io
baseurl: /bbx-tbz
permalink: pretty


### site structure

collections:
  songs:
    output: true
    index: 1
  breaks:
    output: true
    index: 2
    title: beats & breaks
  ltbb:
    output: true
    index: 3
    title: practice beats
    description: from bellatrix's 'learn to beatbox' course


### build settings

theme: jekyll-theme-minimal
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
