
### site meta

title: BBX TBZ<p>ğŸ¤ğŸ¥ğŸµ</p>
description: various beats & breaks, transcribed as tablature for beatboxing
author: lyn malka


### host settings

# omitting http:// at the start forces HTTPS
domain: eliranmal.github.io
url: https://eliranmal.github.io
baseurl: /bbx-tbz
permalink: pretty


### site structure

collections:
  songs:
    output: true
    index: 1
  breaks:
    output: true
    index: 2
    title: beats & breaks
  bbx4w:
    output: true
    index: 3
    title: beatbox in 4 weeks
    description: practice beats from the [course](https://www.learn-to-beatbox.com/) by [bellatrix](https://www.bellatrixmusic.co.uk/about)


### build settings

theme: jekyll-theme-minimal
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
